name: Cypress E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from GitHub Secrets
        run: |
          echo "CYPRESS_email=${{ secrets.CYPRESS_EMAIL }}" >> .env
          echo "CYPRESS_password=${{ secrets.CYPRESS_PASSWORD }}" >> .env
          echo "CYPRESS_API=${{ secrets.CYPRESS_API }}" >> .env

      - name: Run Cypress tests
        env:
          CYPRESS_email: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_API: ${{ secrets.CYPRESS_API }}
          CYPRESS_teamId: ${{ secrets.CYPRESS_teamId }}
        run: npx cypress run

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos